### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by profxj** [AlxLhrNc/pyBOA#1]
Morning -- is this code base still actively developed, maintained?
  I note no new contributions since last year.

please advise.  

If it has gone stale, I am likely to fold it one of my
own Repositories in this Organization:

https://github.com/AI-for-Ocean-Science

**Comment by AlxLhrNc** [comment]
Morning, and apologies for the delay in my response.

Yes it is currently maintained and updated, as I am regularly using it for my own research.
However, as I need the code to remain as is for stability of my current project, I am not pushing a new version yet.

If you need an urgent update, please let me know what is actually the problem you are having, and I will try to address it as fast as possible.

**Comment by profxj** [comment]
all good.  I'll fuss around with it in a few weeks and get back to you.
Am just looking about for now.

Thanks!
